### ISSUE TITLE
import LabelEncoder in submodule needs additional imports in functions list

### ISSUE THREAD

**Issue by kacper1095** [maxpumperla/hyperas#137]
Hi!

I'm struggling currently with following issue. I'm trying to run optimization on model, which uses singleton class that I imported in ran script. This singleton imports and uses LabelEncoder from sklear.preprocessing. I tried successively adding to `functions` more and more classes that LabelEncoder uses (such as `column_or_1d`, and many more). But I stopped at the moment, where I had to import a property, which hyperas `minimize` didn't accept. 

I'm running my script from top module using command
```
python -m src.module.submodule.script
```

Error I get:
```
NameError: name 'column_or_1d' is not defined  
```

**Comment by kacper1095** [comment]
Maybe not the best solution, but I found out that moving my script to top directory and running:
```
python script.py
```
solved all my importing problems. If anyone knows how to deal with a way of running script mentioned earlier, please share this information.

Issue can be closed.

**Comment by maxpumperla** [comment]
sorry for the very late reply. from what I understand from your description, this is not entirely related to hyperas I think. you need to make sure that your script is on your `PYTHONPATH` in some way or the other. If you sit top level in the package you're developing this is the case. Otherwise you need to install that package.
