### ISSUE TITLE
SyntaxErro when run the complete example in Jupter Notebook

### ISSUE THREAD

**Issue by CodeKiller48** [maxpumperla/hyperas#28]
Unexpected error: <type 'exceptions.SyntaxError'>
  File "temp_model.py", line 1
    importers when locating support scripts as well as when importing modules.
                 ^
SyntaxError: invalid syntax

**Comment by lishen** [comment]
I have exactly the same problem. Plus, when I simply copied and pasted the entire example to "hyperas_test.py" and run it in command line, it gave me this error:

> Traceback (most recent call last):
  File "hyperas_test.py", line 77, in <module>
    trials=Trials())
  File "/Users/lishen/anaconda/lib/python2.7/site-packages/hyperas/optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
  File "/Users/lishen/anaconda/lib/python2.7/site-packages/hyperas/optim.py", line 111, in base_minimizer
    rseed=rseed)
TypeError: fmin() got an unexpected keyword argument 'rseed'

My hyperopt version is '0.0.3.dev0'

**Comment by lishen** [comment]
OK. The 'rseed' problem has been fixed in this commit: #30 

I also found the reason to the above error. In short, Hyperas tries to read the content of the calling script to extract the lines that correspond to "import". This works fine for a standalone Python script but pulls many strange lines when runs inside an ipython notebook. It also fails to get the "import" lines correctly.

**Comment by maxpumperla** [comment]
this is supported now, let me know if there's any other problem
