### ISSUE TITLE
The "show_accuracy" argument is deprecated

### ISSUE THREAD

**Issue by jdelange** [maxpumperla/hyperas#56]
> C:\Program Files\Anaconda2\lib\site-packages\keras\models.py:635: UserWarning:
> he "show_accuracy" argument is deprecated, instead you should pass the "accurac
> " metric to the model at compile time:
> `model.compile(optimizer, loss, metrics=["accuracy"])`
>   warnings.warn('The "show_accuracy" argument is deprecated, '

In your example application:

```
model.fit(X_train, Y_train,
              batch_size={{choice([64, 128])}},
              nb_epoch=1,
              show_accuracy=True,
              verbose=2,
              validation_data=(X_test, Y_test))
```

**Comment by isrugeek** [comment]
@jdelange How did you fix this issue i also got this Issue in my Project ( Not this Code)
Thanks in Advance

**Comment by jdelange** [comment]
@isrugeek As noted above: replace the `show_accuracy=True` statement with `metrics=['accuracy']` I'm not sure exactly where this applies, but it is either in the code you are writing, or it is in existing (example) code in Keras/Hyperopt if it has not yet been fixed. Note: I had too many issues with Hyperas, I used Hyperopt instead.

**Comment by isrugeek** [comment]
@jdelange Thanks but after i changed it shows me another error 

> TypeError: Received unknown keyword arguments: {'metrics': ['accuracy']}

**Comment by jdelange** [comment]
@isrugeek Sorry, can't see what you are doing. The syntax provided is correct, so the call may not be applicable/available in your case? Sounds quite basic. Not sure how experienced you are. Have a look at this site [Machine learning mastery](http://machinelearningmastery.com/tutorial-first-neural-network-python-keras/) lots of basic examples to get started. Helped me a lot.

**Comment by isrugeek** [comment]
@jdelange Thanks buddy. i am confused because it works on my different machine and not on MacBook . any how i fixed the problem by edit the Model.py( Keras File)  by comparing my Old machine. 

Thanks

**Comment by JAStark** [comment]
The issue arises from:
`model.fit(X_train,
            y_train_ohe,
            nb_epoch=50,
            batch_size=300,
            verbose=1,
            validation_split=0.1,
            show_metrics=True)
`
which is from a book (Python Machine Learning by @Rabst  https://github.com/rasbt/python-machine-learning-book. It's awesome, but I guess the code gets old quick!)

The new way of doing it means to add `metrics=['accuracy'] to the `model.compile` section, rather than the `model.fit`:

`model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
`
I've just run into this issue, and changing the code in these places worked for me :D

**Comment by rasbt** [comment]
@JAStark The keras section? Oh yeah, that was 2015 :P. The next edition will have up-to-date tensorflow >= 1.0 code ;)

**Comment by JAStark** [comment]
The issue arises from where the code gets edited. 

I came across this problem following code from https://github.com/rasbt/python-machine-learning-book by @rasbt, which is awesome, but I guess the code can get old quickly, sometimes.

`model.fit(X_train,
            y_train_ohe,
            nb_epoch=50,
            batch_size=300,
            verbose=1,
            validation_split=0.1,)
            show_accuracy=True)`

This needs to be changed to `metric=['accuracy']` in the `model.compile` line, rather than the `model.fit` line:

model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])

This worked perfectly for me, returning the output to the screen that I expected from the book. Hope this helps.

**Comment by JAStark** [comment]
@rasbt yes! Chapter 13 :)

**Comment by maxpumperla** [comment]
ok, it's updated now in the readme. Note that you're free to leave out additional arguments in examples as you want, hyperas is just a wrapper, not a prescription. :)

**Comment by beyhangl** [comment]
@JAStark thanks

**Comment by gontthias** [comment]
@JAStark good answer,thanks
